Oracle SQL
Lab Assignment #2 
Katerina Chinappan 
#9292 
Due: 01/20/2016
Handed in: 01/17/2016 

SELECT ENAME, JOB, HIREDATE, EMPNO
	FROM EMP;

SELECT ENAME FROM EMP;
SELECT DISTINCT ENAME FROM EMP;

INSERT INTO EMP (EMPNO, ENAME, JOB, SAL, HIREDATE, DEPTNO, MGR)
   VALUES (1456, 'John Smith', 'Analyst', 2000, '01-JAN-02', 20, 7566);

UPDATE EMP SET SAL=3000 WHERE ENAME='John Smith';

SELECT * FROM EMP
   WHERE ENAME LIKE '%L%L%';

SELECT * FROM EMP
   WHERE ENAME LIKE '%L%L%'
   AND TRIM(ENAME)LIKE '%N';

SELECT * FROM DEPT
   WHERE LOC LIKE 'BOSTON%';

SELECT * FROM EMP
   WHERE DEPTNO LIKE '10%' AND JOB NOT LIKE 'MANAGER%' AND JOB NOT LIKE 'CLERK%';

SELECT * FROM EMP
    WHERE COMM > 0 AND SAL BETWEEN 1000 AND 3000;

SELECT * FROM EMP
     WHERE MGR IS NULL;

SELECT * FROM EMP
    WHERE MGR LIKE '7566%'
    OR MGR LIKE '7788%';
